fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\UserEntity
    from_email:
        address: "jeremy.bourgin@etu.umontpellier.fr"
        sender_name: "jeremy.bourgin@etu.umontpellier.fr"
    registration:
        confirmation:
            enabled: false
